# Site settings
paginate: 4
paginate_path: "/blog/page:num/"
encoding: utf-8
# Build settings
markdown: redcarpet
redcarpet:
  extensions: ['footnotes', 'tables', 'no_intra_emphasis', 'autolink']
jekyll-archives:
  enabled: [tags]
  layout: tag
  permalinks:
    tag: '/blog/tag/:name/'
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title
      excerpt_separator: <div id="more"></div> 
  - scope:
      path: ""
      type: hacks
    values:
      layout: hack
      permalink: /:collection/:title/
collections:
  hacks:
    output: true
