title: 'hennevogel.de'
description: 'Personal blog of Henne Vogelsang'
url: 'https://hennevogel.de'
paginate: 4
paginate_path: "/blog/page:num/"
encoding: utf-8
markdown: redcarpet
redcarpet:
  extensions: ['footnotes', 'tables', 'no_intra_emphasis', 'autolink']
jekyll-archives:
  enabled: [tags]
  layout: tag
  permalinks:
    tag: '/blog/tag/:name/'
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: /blog/:title.html
      excerpt_separator: <div id="more"></div>
  - scope:
      path: ""
      type: hacks
    values:
      layout: hack
      permalink: /:collection/:title/
collections:
  hacks:
    output: false

assets:
  digest: true
  assets:
    - "*.ttf"
    - "*.eot"
    - "*.woff"
    - "*.woff2"
    - "*.svg"
    - "*.png"
    - "*.jpg"
  sources:
    - _assets/css
    - _assets/images
    - _assets/fonts
# https://github.com/jekyll/jekyll/issues/2938
exclude: [vendor, Gemfile, Gemfile.lock, README.md, bin, config]
